In [1]:
import numpy as np

In [8]:
data = np.loadtxt("data/spambase.data", dtype='f', delimiter=',')

print (data)

max_value_in_data = [ 0 ] * 58

for lin in data:
    for x in range(0, 58):
        max_value_in_data[x] = max( max_value_in_data[x], lin[x] )
        
max_value_in_data

[[0.000e+00 6.400e-01 6.400e-01 ... 6.100e+01 2.780e+02 1.000e+00]
 [2.100e-01 2.800e-01 5.000e-01 ... 1.010e+02 1.028e+03 1.000e+00]
 [6.000e-02 0.000e+00 7.100e-01 ... 4.850e+02 2.259e+03 1.000e+00]
 ...
 [3.000e-01 0.000e+00 3.000e-01 ... 6.000e+00 1.180e+02 0.000e+00]
 [9.600e-01 0.000e+00 0.000e+00 ... 5.000e+00 7.800e+01 0.000e+00]
 [0.000e+00 0.000e+00 6.500e-01 ... 5.000e+00 4.000e+01 0.000e+00]]


[4.54,
 14.28,
 5.1,
 42.81,
 10.0,
 5.88,
 7.27,
 11.11,
 5.26,
 18.18,
 2.61,
 9.67,
 5.55,
 10.0,
 4.41,
 20.0,
 7.14,
 9.09,
 18.75,
 18.18,
 11.11,
 17.1,
 5.45,
 12.5,
 20.83,
 16.66,
 33.33,
 9.09,
 14.28,
 5.88,
 12.5,
 4.76,
 18.18,
 4.76,
 20.0,
 7.69,
 6.89,
 8.33,
 11.11,
 4.76,
 7.14,
 14.28,
 3.57,
 20.0,
 21.42,
 22.05,
 2.17,
 10.0,
 4.385,
 9.752,
 4.081,
 32.478,
 6.003,
 19.829,
 1102.5,
 9989.0,
 15841.0,
 1.0]

4601